name: Release (NPM)

on:
  push:
    branches:
      - main

jobs:
  release-npm:
    name: Build, Version & Publish
    runs-on: ubuntu-latest

    # Required permissions for Changesets
    permissions:
      contents: write
      pull-requests: write
      packages: write

    if: github.event.repository.fork == false

    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      # Check if the token is present
      - name: Check Token
        run: |
          if [ -z "$NODE_AUTH_TOKEN" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN IS PRESENT"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          scope: '@systemix'
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Install Dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build packages
      - name: Build project
        run: pnpm build

      # Version + Publish via Changesets
      - name: Version & Publish Packages
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
